CREATE TABLE CONFIGURATION (
    CLUSTER_NAME VARCHAR NOT NULL,
    BOOTSTRAP_SERVER VARCHAR NOT NULL,
    ZOOKEEPER VARCHAR,
    ADDITIONAL_PROPERTIES VARCHAR,
    COLOR VARCHAR,
    SCHEMA_REGISTRY_URL VARCHAR,
    SCHEMA_REGISTRY_SECURITY_TYPE VARCHAR,
    SCHEMA_REGISTRY_SECURITY_USER VARCHAR,
    SCHEMA_REGISTRY_SECURITY_PASS VARCHAR,
    SCHEMA_REGISTRY_SECURITY_TOKEN VARCHAR,
    SCHEMA_REGISTRY_ADDITIONAL_PROPERTIES VARCHAR,
    PRIMARY KEY (CLUSTER_NAME)
);

CREATE TABLE KAFKA_CONNECT (
    ID IDENTITY NOT NULL PRIMARY KEY,
    NAME VARCHAR NOT NULL,
    URL VARCHAR NOT NULL,
    HTTP_HEADERS VARCHAR NULL,
    SECURITY_TYPE  VARCHAR NULL,
    SECURITY_USER VARCHAR NULL,
    SECURITY_TOKEN VARCHAR NULL,
    SECURITY_PASS VARCHAR NULL,
    ADDITIONAL_PROPERTIES VARCHAR NULL,
    ID_CONFIGURATION VARCHAR NOT NULL,

    FOREIGN KEY (ID_CONFIGURATION) REFERENCES CONFIGURATION(CLUSTER_NAME)
);

